CREATE TABLE IF NOT EXISTS `form_admission_database` (
  `id` bigint(20) NOT NULL ,
  `date` DATE DEFAULT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `encounter` varchar(255) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `Transfusion_policy_reviewed` tinyint(1) DEFAULT NULL,
  `blood_product` varchar(50) DEFAULT NULL,
  `current consent signed` tinyint(1) DEFAULT NULL,
  `verfiy blood type with type and cross` tinyint(1) DEFAULT NULL,
  `patient blood type` text,
  `premed given if ordered?` tinyint(1) DEFAULT NULL,
  `Tempdot white if applicable` tinyint(1) DEFAULT NULL,
  `compare blood product with provider order` tinyint(1) DEFAULT NULL,
  `verify compatibility` tinyint(1) DEFAULT NULL,
  `verify volume with order` tinyint(1) DEFAULT NULL,
  `verify special requirements match` tinyint(1) DEFAULT NULL,
  `issue time confirmed` tinyint(1) DEFAULT NULL
  `issue date confirmed` tinyint(1) DEFAULT NULL,
  `Indications for transfusion` text,
  `Patient identifiers confirmed`  tinyint(1) DEFAULT NULL,
  `compare tag info to requisition` tinyint(1) DEFAULT NULL,
  `compare bag to requsition` tinyint(1) DEFAULT NULL
  `dual verification of blood completed` tinyint(1) DEFAULT NULL,
  `2nd verifiers name or initials` varchar(50),
  `verification done at the bedside` tinyint(1) DEFAULT NULL,
  `time transfusion started` varchar(20),
  `Temperature` varchar(20),
  `Pulse` varchar(10),
  `Respirations` varchar(10),
  `Blood Pressure` varchar(10),
  `SpO2` 				varchar(10),
  `Respiratory pattern` varchar(255),
  `Retractions`  tinyint(1) DEFAULT NULL,
  `cough` varchar(255),
  `appearance` varchar(255) DEFAULT NULL,
  `Breath sounds RUL` varchar(255) DEFAULT NULL,
  `Breath sounds RML` varchar(255) DEFAULT NULL,
  `Breath sounds RLL` varchar(255) DEFAULT NULL,
  `Breath sounds LUL` varchar(255) DEFAULT NULL,
  `Breath sounds LLL` varchar(255) DEFAULT NULL,
  `Rash location` varchar(255) DEFAULT NULL,
  `Rash description` varchar(255) DEFAULT NULL,
  `Transfusion stop time` DATE DEFAULT NULL,
  `Transfusion reason`  varchar(255) DEFAULT NULL,
  `1 hour post transfusion vitals completed` tinyint(1) DEFAULT NULL,
  `Post discharge instructions given` tinyint(1) DEFAULT NULL,
  `Suspected transfusion reaction (y/n)` varchar(255) DEFAULT NULL,
) ENGINE=InnoDB;