CREATE TABLE IF NOT EXISTS `form_transfusions` (
  `id` bigint(20) NOT NULL ,
  `date` DATE DEFAULT NULL,
  `pid` bigint(20) DEFAULT NULL,
  `encounter` varchar(255) DEFAULT NULL,
  `user` varchar(255) DEFAULT NULL,
  `groupname` varchar(255) DEFAULT NULL,
  `authorized` tinyint(4) DEFAULT NULL,
  `activity` tinyint(4) DEFAULT NULL,
  `Transfusion_policy_reviewed` tinyint(1) DEFAULT NULL,
  `blood_product` varchar(50) DEFAULT NULL,
  `current_consent_signed` tinyint(1) DEFAULT NULL,
  `verfiy_blood_type_with_type_and_cross` tinyint(1) DEFAULT NULL,
  `patient_blood_type` varchar(255) DEFAULT NULL,
  `premed_given_if_ordered?` tinyint(1) DEFAULT NULL,
  `Tempdot_white_if_applicable` tinyint(1) DEFAULT NULL,
  `compare_blood_product_with_provider_order` tinyint(1) DEFAULT NULL,
  `verify_compatibility` tinyint(1) DEFAULT NULL,
  `verify_volume_with_order` tinyint(1) DEFAULT NULL,
  `verify_special_requirements_match` tinyint(1) DEFAULT NULL,
  `issue_time_confirmed` tinyint(1) DEFAULT NULL,
  `issue_date_confirmed` tinyint(1) DEFAULT NULL,
  `Indications_for_transfusion` varchar(255) DEFAULT NULL,
  `Patient_identifiers_confirmed`  tinyint(1) DEFAULT NULL,
  `compare_tag_info_to_requisition` tinyint(1) DEFAULT NULL,
  `compare_bag_to_requsition` tinyint(1) DEFAULT NULL,
  `dual_verification_of_blood_completed` tinyint(1) DEFAULT NULL,
  `2nd_verifiers_name_or_initials` varchar(50),
  `verification_done_at_the_bedside` tinyint(1) DEFAULT NULL,
  `time_transfusion_started`                        varchar(20) DEFAULT NULL,
  `Temperature`                                     varchar(20) DEFAULT NULL,
  `Pulse`                                           varchar(10) DEFAULT NULL,
  `Respirations` varchar(10) DEFAULT NULL,
  `Blood_Pressure` varchar(10) DEFAULT NULL,
  `SpO2` 				varchar(10) DEFAULT NULL,
  `Respiratory_pattern` varchar(255),
  `Retractions`  tinyint(1) DEFAULT NULL,
  `cough` varchar(255) DEFAULT NULL,
  `appearance` varchar(255) DEFAULT NULL,
  `Breath_sounds_RUL` varchar(255) DEFAULT NULL,
  `Breath_sounds_RML` varchar(255) DEFAULT NULL,
  `Breath_sounds_RLL` varchar(255) DEFAULT NULL,
  `Breath_sounds_LUL` varchar(255) DEFAULT NULL,
  `Breath_sounds_LLL` varchar(255) DEFAULT NULL,
  `Rash_location`varchar(255) DEFAULT NULL,
  `Rash_description` varchar(255) DEFAULT NULL,
  `Transfusion_stop_time` DATE DEFAULT NULL,
  `Transfusion_reason`  varchar(255) DEFAULT NULL,
  `1_hour_post_transfusion_vitals_completed` tinyint(1) DEFAULT NULL,
  `Post_discharge_instructions_given` tinyint(1) DEFAULT NULL,
  `Suspected_transfusion_reaction___y__n____` varchar(255) DEFAULT NULL
) ENGINE=InnoDB;